version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "atomically"
      - dependency-name: "axios"
      - dependency-name: "nanoid"
